name = "myp-worker"
main = "worker.js"
compatibility_date = "2025-08-24"

[[d1_databases]]
binding = "DB"                   # это то, что используешь в коде (env.DB)
database_name = "myp"            # имя твоей базы в Cloudflare
database_id = "8918abda-4b32-4dce-bf9a-036daf2aca1e"  # твой databaseId
